### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by SiverDX** [CCr4ft3r/EnhancedBlockEntitiesReforged#4] opened 2023-04-30 11:56 UTC
Heavily modded pack but it's about `minecraft:oak_wall_sign`
* EnhancedBlockEntities-Reforged-1.19.2-0.7.2.jar
* brrp-forge-0.9.0-1.19.2.jar
* reforgium-1.0.12a.jar
* rubidium-0.6.2a.jar

Crash happened when I got near a village (from `Better Villages` or `Towns and Towers` or maybe something else, not sure)

```
Reported exception thrown!
net.minecraft.ReportedException: Rendering Block Entity
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:111)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:79)
	at TRANSFORMER/oculus@1.2.8a/net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:550)
	at TRANSFORMER/oculus@1.2.8a/net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:472)
	at TRANSFORMER/oculus@1.2.8a/net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:631)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.handler$bad000$iris$renderTerrainShadows(LevelRenderer.java:11161)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.8/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:oak_wall_sign}
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98)
	at TRANSFORMER/enhancedblockentities@1.19.2-0.7.2/foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.render(SignBlockEntityRendererOverride.java:44)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.handler$eoa000$enhanced_bes$renderOverrides(BlockEntityRenderDispatcher.java:3047)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:79)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:104)
	... 25 more
```

**Comment by CCr4ft3r** [comment] 2023-04-30 12:28
Duplicate of https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/issues/3
Will be fixed asap.

**Closed as completed by CCr4ft3r** 2023-04-30 12:28 UTC
