### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by jogurciQ** [CCr4ft3r/EnhancedBlockEntitiesReforged#9] opened 2023-05-12 09:33 UTC
Probably some mod compatibility issue or something i dunno

[crash-2023-05-12_11.29.11-client.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11461613/crash-2023-05-12_11.29.11-client.txt)

**Comment by CCr4ft3r** [comment] 2023-05-12 09:53
duplicate of #6

**Closed as completed by CCr4ft3r** 2023-05-12 09:53 UTC
