### ISSUE TITLE
I get crashes with 1.18.2

### ISSUE THREAD

**Issue by u7f8au7fbd** [CCr4ft3r/EnhancedBlockEntitiesReforged#7] opened 2023-05-08 12:51 UTC
You get a crash report that says 

"The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: net/devtech/arrp/api/RuntimeResourcePack" 

This occurred without using any other mods.

**Comment by CCr4ft3r** [comment] 2023-05-08 14:08
You need BRRP <= 0.9.0

**Comment by CCr4ft3r** [comment] 2023-05-08 14:08
duplicate of https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/issues/6

**Comment by CCr4ft3r** [comment] 2023-05-08 21:07
Also need Rubidium

**Closed as completed by CCr4ft3r** 2023-05-08 21:07 UTC
